{% set name = "pyhacrf-datamade" %}
{% set version = "0.2.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: bbbee0ea756d6118d62de3731c9f713106ba49b14eafb01b88e87aa5b962f201

build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - cython
    - numpy
    - pip
    - python
  run:
    - pylbfgs
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pyhacrf
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dedupeio/pyhacrf
  summary: Hidden alignment conditional random field, a discriminative string edit distance
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - osamples
    - izahn
